version: '3.8'

services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_sail
    ports:
      - "8001:80"
    environment:
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis

  apache:
    image: 'webdevops/php-apache:alpine'
    ports:
      - "8000:80"
    volumes:
      - '.:/var/www/html'
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - sail

  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'spassu'
      MYSQL_USER: 'spassu'
      MYSQL_PASSWORD: 'spassu'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - sail

  node:
    image: 'node:16-alpine'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    command: sh -c "rm -rf node_modules package-lock.json && npm install && npm run dev"

networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
    driver: local
