version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
     environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=spassu
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
