version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: spassu
            MYSQL_PASSWORD:
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        networks:
            - laravel-network

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8000:80"
        networks:
            - laravel-network
        depends_on:
            - app

networks:
    laravel-network:
        driver: bridge
